<!-- Must needed plugins to the run this Template -->
<script src="<?= urlOf('admin/assets/js/jquery.min.js'); ?>"></script>
<script src="<?= urlOf('admin/assets/js/bootstrap.bundle.min.js'); ?>"></script>
<script src="<?= urlOf('admin/assets/js/default-assets/setting.js'); ?>"></script>
<script src="<?= urlOf('admin/assets/js/default-assets/scrool-bar.js'); ?>"></script>
<script src="<?= urlOf('admin/assets/js/todo-list.js'); ?>"></script>
<script src="<?= urlOf('admin/assets/js/default-assets/top-menu.js'); ?>"></script>
<script src="<?= urlOf('admin/assets/js/default-assets/active.js'); ?>"></script>
<script src="<?= urlOf('admin/assets/js/apexcharts.min.js'); ?>"></script>
<script src="<?= urlOf('admin/assets/js/intro.min.js'); ?>"></script>
<script src="<?= urlOf('admin/assets/js/dashboard-custom.js'); ?>"></script>
<script src="<?= urlOf('admin/assets/js/intro-active.js'); ?>"></script>
<script src="<?= urlOf('admin/assets/js/jquery.dataTables.min.js') ?>"></script>
<script src="<?= urlOf('admin/assets/js/dataTables.bootstrap5.min.js') ?>"></script>
<script src="<?= urlOf('admin/assets/js/dataTables.responsive.min.js') ?>"></script>
<script src="<?= urlOf('admin/assets/js/dataTables.buttons.min.js') ?>"></script>
<script src="<?= urlOf('admin/assets/js/buttons.print.min.js') ?>"></script>
<script src="<?= urlOf('admin/assets/js/pdfmake.min.js') ?>"></script>
<script src="<?= urlOf('admin/assets/js/vfs_fonts.js') ?>"></script>
<script src="<?= urlOf('admin/assets/js/buttons.html5.min.js') ?>"></script>
<script src="<?= urlOf('admin/assets/js/jszip.min.js') ?>"></script>
<script src="<?= urlOf('admin/assets/js/dataTables-custom.js') ?>"></script>